### ISSUE TITLE
The comment issue link is under the gravatar

### ISSUE THREAD

**Issue by pasqualedante** [akabekobeko/redmine-theme-minimalflat2#146]
With 1.5 release I cannot see the comment number in a ticket: the comment link it's under the gravatar icon.
<img width="487" alt="rr" src="https://user-images.githubusercontent.com/813690/53482241-16d7a680-3a7f-11e9-8e26-d58e6f510e09.png">

**Comment by akabekobeko** [comment]
@pasqualedante 

The current Redmine is displayed with the comment number on the right. Therefore, this issue is not considered a bug. This layout seems to have been at least around Redmine v3.4.

If the display is strange, it may be a problem with CSS caching. In that case, please try super reloading of the web browser.

**minimalflat2**

![ss-01](https://user-images.githubusercontent.com/1257526/54509701-c96b9c80-498d-11e9-957a-c9ac9bffc354.png)

**Default (Redmine v4.0)**

![ss-02](https://user-images.githubusercontent.com/1257526/54509824-3a12b900-498e-11e9-875b-75f45ae190a8.png)
