### ISSUE TITLE
gantt chart page link error

### ISSUE THREAD

**Issue by whoppercrab** [akabekobeko/redmine-theme-minimalflat2#159]
Disable left side hyperlinks in Gantt chart pages. The hyperlink tag is added but does not work.

**Comment by akabekobeko** [comment]
@whoppercrab 
Would you like to add information on the environment and phenomena as I would like to investigate?

- Redmine and minimalflat2 versions
- Steps to reproduce the phenomenon
- Screenshot of the screen where the phenomenon occurred

**Comment by whoppercrab** [comment]
@akabekobeko 
Thank you for answer 

Redmine and minimalflat2 versions
->
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
  redmine-theme-minimalflat2 version  1.7.0
Steps to reproduce the phenomenon
Screenshot of the screen where the phenomenon occurred
-->
 ipaddress:port/redmine/issues/gantt page

![제목 없음](https://user-images.githubusercontent.com/13113942/75300598-c22a5f80-587b-11ea-9a24-79216063a093.png)
The black line is clickable. The red line is not clickable.

**Comment by akabekobeko** [comment]
@whoppercrab 

minimalflat2 supports only the latest Redmine at the time of release. This is because the Redmine standard theme itself is not compatible in the past.

If update CSS as the HTML structure of Redmine itself changes, the operation of the past version cannot be guaranteed.

> Redmine version 3.4.6.stable

If you use this version, it is [minimalflat2 v1.4.0](https://github.com/akabekobeko/redmine-theme-minimalflat2/releases/tag/v1.4.0)
 that has been confirmed to work.

There was a big change in Gantt chart HTML in Redmine v4 series. Therefore, minimalflat2's CSS is also affected (#157) to support it.

**Comment by whoppercrab** [comment]
@akabekobeko 

Thank you
I solved Using minimalflat2 v1.4.0
