### ISSUE TITLE
Change font-size from em to px?

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#77]
Hi,

The main text font-size of the theme is quit big to me but I didn't find the way to reduce it. I checked and it is 16px but I cannot find the CSS code for main text font.
(I was able to add it by add font-size: 16px to body tag)
Please help.

Thanks.

**Comment by akabekobeko** [comment]
The Stylus and normalize.css was grep in the `font-size`. As a result, it had specified 16px in `App.styl`.

```stylus
/***** Projects ******/
#projects-index ul.projects {
  div.root a.project {
    font-weight bold
    font-size 16px
    margin 0 0 10px 0
  }
}
```

But this is not the main text. It is a link of the root project name of the project list.

This theme is specified em rather than as much as possible px to the `font-size`. So, this 16px is corrected to 1em.

**Comment by akabekobeko** [comment]
"main text" is I want you to tell me refer to any screen. 
Easy to understand that there is a specified by the CSS class name or HTML DOM if possible.

**Comment by akabekobeko** [comment]
`16px` to the `body` in this theme is not set. But it was deleted because there was a `font-size:16px` at the root of the project list.
